export const UPDATE_FAVORITES_ATTEMPTED = "UPDATE_FAVORITES_ATTEMPTED";
export const UPDATE_FAVORITES_SUCCESSFUL = "UPDATE_FAVORITES_SUCCESSFUL";
export const UPDATE_FAVORITES_FAILED = "UPDATE_FAVORITES_FAILED";

export const UPDATE_FAV_ATTEMPTED = "UPDATE_FAV_ATTEMPTED";
export const UPDATE_FAV_SUCCESSFUL = "UPDATE_FAV_SUCCESSFUL";
export const UPDATE_FAV_FAILED = "UPDATE_FAV_FAILED";
