export const AUTHENTICATION_ATTEMPTED = "AUTHENTICATION_ATTEMPTED";
export const AUTHENTICATION_SUCCESSFUL = "AUTHENTICATION_SUCCESSFUL";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"; 